\RequirePackage{ifpdf}
\documentclass[journal]{vgtc}\usepackage{graphicx, color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.2, 0.2, 0.2}
\newcommand{\hlnumber}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlfunctioncall}[1]{\textcolor[rgb]{0.501960784313725,0,0.329411764705882}{\textbf{#1}}}%
\newcommand{\hlstring}[1]{\textcolor[rgb]{0.6,0.6,1}{#1}}%
\newcommand{\hlkeyword}[1]{\textcolor[rgb]{0,0,0}{\textbf{#1}}}%
\newcommand{\hlargument}[1]{\textcolor[rgb]{0.690196078431373,0.250980392156863,0.0196078431372549}{#1}}%
\newcommand{\hlcomment}[1]{\textcolor[rgb]{0.180392156862745,0.6,0.341176470588235}{#1}}%
\newcommand{\hlroxygencomment}[1]{\textcolor[rgb]{0.43921568627451,0.47843137254902,0.701960784313725}{#1}}%
\newcommand{\hlformalargs}[1]{\textcolor[rgb]{0.690196078431373,0.250980392156863,0.0196078431372549}{#1}}%
\newcommand{\hleqformalargs}[1]{\textcolor[rgb]{0.690196078431373,0.250980392156863,0.0196078431372549}{#1}}%
\newcommand{\hlassignement}[1]{\textcolor[rgb]{0,0,0}{\textbf{#1}}}%
\newcommand{\hlpackage}[1]{\textcolor[rgb]{0.588235294117647,0.709803921568627,0.145098039215686}{#1}}%
\newcommand{\hlslot}[1]{\textit{#1}}%
\newcommand{\hlsymbol}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlprompt}[1]{\textcolor[rgb]{0.2,0.2,0.2}{#1}}%

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}                % final (journal style)
%\documentclass[review,journal]{vgtc}         % review (journal style)

\usepackage{natbib}
\usepackage{mathptmx}
\usepackage{graphicx}
\usepackage{times}
\usepackage{amsmath}
\usepackage{multirow}
%\usepackage{knitr}
\usepackage{url}
\usepackage[table]{xcolor}

\renewcommand\floatpagefraction{1}

%% We encourage the use of mathptmx for consistent usage of times font
%% throughout the proceedings. However, if you encounter conflicts
%% with other math-related packages, you may want to disable it.

%% If you are submitting a paper to a conference for review with a double
%% blind reviewing process, please replace the value ``0'' below with your
%% OnlineID. Otherwise, you may safely leave it at ``0''.
\onlineid{224}

%% declare the category of your paper, only shown in review mode
\vgtccategory{Research}

%% allow for this line if you want the electronic option to work properly
\vgtcinsertpkg

%% In preprint mode you may define your own headline.
%\preprinttext{To appear in an IEEE VGTC sponsored conference.}

%% Paper title.

\title{Common Angle Plots as perception-true visualizations of categorical associations}

%% This is how authors are specified in the journal style

%% indicate IEEE Member or Student Member in form indicated below
\author{Heike Hofmann, Marie Vendettuoli}
\authorfooter{
%% insert punctuation at end of each item
\item
 Heike Hofmann is  Professor of Statistics and faculty member in the Human Computer Interaction program at Iowa State University, E-mail: hofmann@iastate.edu.
\item
Marie Vendettuoli is a graduate student at Iowa State University, with majors in Human Computer Interaction and Bioinfomatics \& Computational Biology. She is a past IGERT Fellow and currently interns with the Statistics section at USDA.  E-mail: mariev@iastate.edu.
}

%other entries to be set up for journal
\shortauthortitle{Hofmann \MakeLowercase{\textit{et al.}}: Common Angle Plots}
%\shortauthortitle{Firstauthor \MakeLowercase{\textit{et al.}}: Paper Title}

%% Abstract section.
\abstract{
Visualizations are great tools of communications - they summarize findings and quickly convey main messages to our audience. As designers of charts we have to make sure that information is shown with a minimum of distortion. We have to also consider illusions and other perceptual  limitations of our audience. In this paper we discuss  the effect and strength of the  line width illusion,  a M\"uller-Lyer type illusion, on designs related to displaying associations between categorical variables. Parallel sets and hammock plots are both affected by line width illusions. We  introduce the common-angle plot as an alternative method for displaying categorical data in a manner that minimizes the effect from perceptual illusions. Results from user studies both highlight the need for addressing  line-width illusions in displays and provide evidence that common angle charts successfully resolve this issue.
} % end of abstract

%% Keywords that describe your work. Will show as 'Index Terms' in journal
%% please capitalize first letter and insert punctuation after last keyword
\keywords{Linewidth illusion, Data Visualization, High-dimensional Displays, Parallel Sets, Hammock Plots, M\"uller-Lyer Illusion.}

%% ACM Computing Classification System (CCS). 
%% See <http://www.acm.org/class/1998/> for details.
%% The ``\CCScat'' command takes four arguments.

\CCScatlist{ % not used in journal version
  \category{H.5.2}{Information Interfaces and Presentation}{ User Interfaces --- Graphical user interfaces (GUI), Interaction styles, Screen design, Evaluation/methodology}
  \CCScat{I.6.8}{Computing Methodologies}%
  {Simulation and Modeling}{Visual Simulation};
}

\graphicspath{{images/}}
\definecolor{LightGrey}{gray}{0.9}

%% Uncomment below to include a teaser figure.
\teaser{
\centering
\includegraphics[height=1.5in]{ca-titanic-teaser.pdf}\hspace{0.01\linewidth}
\includegraphics[height=1.5in]{cubes.pdf}
%\includegraphics[width=16cm]{CypressView.eps}
\caption{Who survived on the Titanic? Common Angle plot of survival by class (left). On the right, graphs showing survey results with answers.}
}

%% Uncomment below to disable the manuscript note
%\renewcommand{\manuscriptnotetxt}{}

%% Copyright space is enabled by default as required by guidelines.
%% It is disabled by the 'review' option or via the following command:
% \nocopyrightspace

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%% START OF THE PAPER %%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}

\begin{document}

%% The ``\maketitle'' command must be the first command after the
%% ``\begin{document}'' command. It prepares and prints the title block.

%% the only exception to this rule is the \firstsection command
\firstsection{Introduction}

\maketitle

% !TEX root = common-angle-infovis.tex


% The very first letter is a 2 line initial drop letter followed
% by the rest of the first word in caps.
% 
% form to use if the first word consists of a single letter:
% \IEEEPARstart{A}{demo} file is ....
% 
% form to use if you need the single drop letter followed by
% normal text (unknown if ever used by IEEE):
% \IEEEPARstart{A}{}demo file is ....
% 
% Some journals put the first two words in caps:
% \IEEEPARstart{T}{his demo} file is ....
% 
% Here we have the typical use of a "T" for an initial drop letter
% and "HIS" in caps to complete the first word.
A well-designed graph is a powerful tool 
that transcends barriers of language to
communicate complex concepts from author to audience. 
Problems arise when readers are unable to easily extract a chart's main message or are led to wrong conclusions due to distortions.
Distortions endanger the trust between readers and creators of charts. This trust is based on the  premise that
graphics have to be true to the data \citep{tufte, wainer:2000, robbins:2005}.
There is a lot of discussion on keeping true to the data in the framework of (ab)using three dimensional effects in graphics. \citet{tufte} goes as far as defining the {\it lie-factor} -- the ratio of the size of an effect in the data compared to the size of an effect shown in the chart. Any large deviation of this factor from one indicates a misuse of graphical techniques. Computational tools help us ensure technical trueness -- but this brings up the additional question of how we deal with situations that involve innate inability or trigger learned misperceptions.
One example of distortions of this kind is the 
 M\"{u}ller-Lyer family of illusions, which include contextual illusions,  such as differently perceived lengths of line segments depending on the orientation of arrow heads  
 or the sine illusion~\citep{day:1991}.

Regardless of the cause of distortion, it is the responsibility of the  author of a chart to create visualizations that
 allows readers to extract an accurate interpretation of the underlying data.  In order to gauge the
extent of distortion due to perceptual limitations, we can employ user studies   to provide empirical evidence supporting 
underlying cognitive models or previously unknown or not anticipated illusions.




Parallel sets (parsets)~\citep{kosara:2006} are a graphical method  for visualizing multivariate categorical data. Since their initial publication, parallel sets have spread to mass media outlets ~\citep{eagereyes, bostock:2012, bbc:2009}, have been implemented in various languages~\citep{eagereyes, d3, davies} and are a reputable resource for further academic work \citep[][has 70 citations according to Google scholar]{kosara:2006}. While retaining the %independent 
ability to visualize a large number of dimensions simultaneously that is the parallel coordinates' hallmark trade \cite{inselberg:1985, wegman:1990}, parallel sets combine with it a frequency scale that is a well-known feature of other categorical displays such as barcharts or mosaic plots~\citep{hartigan:1981, friendly:1992, hofmann:2000, theus:1997}. 

Another aspect that parsets allow is the visualization of hierarchies \citep{slingsby:2009, stasko:2000}. They share this ability with mosaicplots and their more general relatives, the treemaps~\citep{shneiderman:1992}, and treemap variants  \citep{bruls:1999, kong:2010, balzer:2005}.


All of these properties make parsets a powerful visualization  in our toolkit, but 
unfortunately, the parallel set plot is a victim of distortion due to a contextual illusion: consider the parset plot of Figure~\ref{question1a}.
%


%
%
\begin{figure}[hbtp]
\centering
%\includegraphics[width=.9\linewidth]{images/parset-titanic}


{\centering \includegraphics[width=.85\linewidth]{images/parset-titanic-col} 

}




\caption{\label{question1a} Parallel sets plot showing the relationship between survival of the sinking of the HMS Titanic and class membership. Class membership and survival are clearly related, but which class had the largest number of survivors? }
\end{figure}
%
%%XXX PS and line-width illusion
This plot shows the relationship between class status and survival on board the HMS Titanic  \citep{dawson:1995}.  The top bar in figure \ref{question1a} shows the  variable Class, recorded as either crew member or passenger in  first, second, or third class. The bottom bar shows survival  as yes and no.
 Lines are drawn between top and bottom bar -- the  (horizontal) width is proportional to the number of survivors and non-survivors they represent. 
 A reasonable task based on this chart is to ask the reader to order class levels according to their number of survivors. However, when study participants were asked to perform this task, only $6.2\%$ of all respondents 
selected the correct order, see table~\ref{raw}, while 37.5\% of all participants agreed on another, incorrect, ordering.

\begin{table}
\begin{center}
\begin{tabular}{rrrrr}
& Crew & 1st & 2nd & 3rd \\ \hline
Survivors & 212 & 203 & 118 & 178\\
Non-Survivors & 673 & 122 & 167 &  528  
\end{tabular}
\caption{Survival status and class membership of all persons on board the HMS Titanic. 
Most survivors were among  crew members, followed by first, third, and, lastly, second class passengers.  }
\end{center}
\end{table}
This phenomenon can be explained by the \emph{line width illusion}. The line-width illusion is a contextual illusion that leads to perceptual distortion in evaluating parallel sets plots. In this paper, we first describe and then quantify this illusion. We also propose and test \emph{common angle plots} as an alternative  method for visualizing multivariate categorical data that helps the audience to avoid the distortional effects of the line width illusion.
%XXX PS and line-width illusion


\section{Line width illusion}


The  phenomenon of the line width illusion  is known and widely discussed in statistical graphics literature \citep{cleveland:1984, tufte, wainer:2000, robbins:2005}. It  is due to our  tendency to assess distance between curves as the minimal (orthogonal) distance rather than the  vertical distance -- see sketch \ref{fig:linewidth} for a visual representation of both.


\begin{figure}
\includegraphics[width=.9\linewidth]{images/playfair_east_indies_gross}
\caption{\label{playfair}
Playfair's chart from the Commercial and Political Atlas (1786) showing the balance of trade between England and the East Indies.  In which years was the difference between imports and exports the highest? }
\end{figure}
On of the earliest examples of the line width illusion is shown in  figure~\ref{playfair}. This chart displays the balance of trade between England and the East Indies as demonstrated by William Playfair in his Commercial and Political Atlas, 1786~\citep{playfair, playfair2}.  One purpose of this chart is to highlight the difference between imports and exports in a particular year and the pattern of these differences over  time. The difference in exports and imports is encoded as the vertical difference between the lines. When observers are asked to sketch out the difference between exports and imports  \citep{cleveland:1984}, they very often  miss the steep rise in the difference between the lines in the years between about 1755 and 1765. Figure \ref{playfair2} shows the  actual difference between imports and exports. 



\begin{figure}
\centering
\includegraphics[width=.8\linewidth, height=.4\linewidth]{images/playfair_differenz_cleveland}
\caption{\label{playfair2}
Difference between exports and imports from England to and from the East Indies in the 18th century -- the steep rise in the difference around 1760  comes as a surprise to many viewers of the raw data in figure \ref{playfair}.  }
\end{figure}




In the perception literature, this phenomenon is known as part of a group of geometrical optical misperceptions of a context-sensitive nature classified as M\"uller-Lyer illusions \citep{day:1991, goldstein}. Interestingly, there seems to be a general agreement that this illusion exists, but a quantification of it is curiously absent from literature. 

The type of chart as shown in figure~\ref{playfair} proposed by Playfair is a quite common occurrence, particular in election years -- where these kind of charts are used to enable comparisons of support for different candidates. The recommendation from literature is to avoid charts in which the audience is asked to do visual subtractions, and show these differences directly \citep{cleveland:1984, wainer:2000, tufte}.

\subsection{Strength of  line width illusion}\label{distortion}

%The difference between perceived and actual line width 
When visually evaluating lines of thickness greater than one, the line width illusion applies. %, only now the {\it edges} of a single line  take on the role of the separate curves. %in the parallel sets 
As above, there is a strong preference of evaluating the width of lines orthogonal to their slopes as opposed to horizontally (see figure \ref{fig:linewidth}), which would lead us to a correct  evaluation of parallel sets-style displays.

Orthogonal $w_o$ and horizontal $w_h$ line widths are related -- the orthogonal line width depends on the angle (or, equivalently, the slope) of the line:
\begin{equation}\label{adjust}
w_o = w_h \sin \theta,
\end{equation}
where $\theta$ is the angle of the line with respect to the horizontal line.

\begin{figure}[htbp]
\begin{center}
\includegraphics[width=0.6\linewidth]{images/linewidth}
\end{center}
\caption{\label{fig:linewidth}Sketch of line width assessments: (a) is showing  horizontal width, (b) shows  width orthogonal to the slope. Survey results in section \ref{results}  indicate that observers associate line width more with  orthogonal width $w_o$ (b) than horizontal width $w_h$ (a).}
\end{figure}



%XXX aspect ratio


\begin{figure*}[htbp]
\begin{center}
\includegraphics[height=1.5in]{images/aspect31-titanic.pdf}
\includegraphics[height=1.5in]{images/aspect33-titanic.pdf}
\end{center}
\caption{\label{fig:aspect}Parallel sets plots of survival on the Titanic by class. Different aspect ratios  seemingly change the thickness of line segments, compare e.g. number of survivors in 3rd class and in the crew. }
\end{figure*}



The perceived slope of a line depends on the aspect ratio of the corresponding plot -- changing the height to width ratio of a display  will change our perception of the corresponding line widths, if they are not adjusted for the slope \citep{cleveland:1984}. This finding is not new, but its strength on our perception is surprising, as can be seen in the example of  figure \ref{fig:aspect}.  Again, survival and class membership on the Titanic is shown; the same parallel sets plot is shown twice in this figure, but with very different aspect ratios: in the  plot on the left the number of surviving 3rd class passengers seems to be about twice as big as the number of survivors among crew members, whereas in the plot on the right the lines have about equal (orthogonal) width. The numbers underlying the figures are identical. Any perceived change is purely due to the different  aspect ratios. 

For parallel sets-style displays, the audience has the {\it area of the line segment} as an alternate visual cue when evaluating frequencies. Because height (or width for a rotated display) of  line segments is constant across the display, the width of a particular  segment is proportional to its area. We could therefore employ area comparisons as a proxy or to augment line width evaluations. 
However, existing literature suggests that this method of comparison is particularly  prone to errors in two scenarios commonly seen in parallel sets: (1) for extreme aspect ratios of the rectangular shape \citep{heer:2010} %occupied by thick line segments 
and (2) when comparing rectangles rotated relative to each other \citep{kong:2010}. 
This incorrect perception and comparison of areas distorts the message readers discern from the graph. %additional contextual evidence that reinforce and strengthen distortion introduced by the line width illusion.


\subsection{Hammock Plots}


Hammock plots, introduced by M Schonlau in \citep{schonlau:2003}, provide an alternative to parallel sets that is adjusted for the line width illusion. This is done by  adjusting the { \it horizontal} line width by  a factor of $\sin \theta$, as discussed in equation (\ref{adjust}). This adjustment makes the perceived {\it orthogonal} line width to be proportional to the number of observations it represents. 
 Figure \ref{hammock} shows an example of a four dimensional hammock plot of the Titanic data. From top to bottom Class, Gender, Survival, and again Class are shown. 
\begin{figure}
% cols <- c(brewer.pal(name="Blues", 6)[-c(1,2)],  rev(brewer.pal(name="Greens",3)[-1]), rev(brewer.pal(name="Oranges", 3)[-1]))
% ggparallel(names(titanic)[c(1,4,2,1)], order=c(0,1,1,0), method="hammock", ratio=.25, text.angle=0, titanic, weight="Freq") +
%  scale_fill_manual(values=cols, guide="none") +
%  scale_colour_manual(values=cols, guide="none") + coord_flip() + theme_bw()
%ggsave("hammock-titanic.pdf", width=6, height=8)
\centering
\includegraphics[width=\linewidth]{images/hammock-titanic}
\caption{\label{hammock} Hammock plot of the relationship between Class and Survival on the Titanic. }
\end{figure}

Similarly to the parallel sets plot, the bars are divided according to class membership numbers.  Lines connect categories between neighboring variables, orthogonal line widths  represent the number of individuals in each combination. Unlike the parallel sets, the lines start from the middle of the bin and connect to the middle of the other variable's bins. This convention is in part due to the fact that the sum of  horizontal widths ($w_h$) after adjustment is greater than the width of marginal bars.

The graph shows that barely any women were in the crew, while male crew members make up the second largest contingent overall. While overall a few more men survived than women, proportionally the situation is much different -- a much higher percentage of women survived than men. While more first class passengers survived than not, the  survival chances of second class passengers were evenly divided. For third class passengers and crew members fewer members did  survive than not. 

As the adjustment of line widths is made with respect to the angle $\theta$, which itself depends on the aspect ratio of a plot, we need complete control over these properties of the plotting device when constructing hammock plots  -- in our implementation (see below for details) we have dealt with this issue by fixing the aspect ratio. This is problematic in some situations, where the rendering has to be done without knowledge of the plotting device. 



\subsection{Reverse linewidth}
A problem that arises in evaluating hammock plots is that if an observer focuses on horizontal line width  the plots suffer from a {\it reverse line width illusion}:  judging the number of survivors by class in figures \ref{hammock} and \ref{hammock_zoom} based on horizontal line width  results in an ordering of (largest to smallest) Crew, 3rd, 1st, and 2nd -- which is not correct either. %Using horizontal width is inviting, since the lines are centered around the middle of a level, im
Because the lines are centered around the middle of each level, a contextual coordinate system is imposed that encourages comparisons of horizontal width. However, horizontal width is no longer proportional to underlying data, because of the line width adjustment.  
The amount of distortion perceived can be quantified by rearranging equation \ref{adjust}:
\begin{equation}\label{rev}
w_h = w_o \csc \theta,
\end{equation}
 where $w_o$ is proportional to observations and $\theta$ is the angle of the line with respect to the horizontal line.

\begin{figure}[htbp]
\centering
\includegraphics[width = .75\linewidth]{images/grid-hammock-zoom}
\caption{\label{hammock_zoom}Lines in hammock plot of Titanic data for survival variable, level yes. Comparing horizontal widths suggests that a greater number of survivors were from third class instead of first, which is inconsistent with underlying data.}
\end{figure}


%
%\section{Overview}
%From previous work~\citep{cleveland:1984, tufte, wainer:2000, robbins:2005, heer:2010, kong:2010}, we may conclude that numerically accurate representations of data
%are subject to distortion due to perceptual limitations. In particular,
%the width of a single line of some thickness or the distance between two lines of minimal thickness is 
%subject to the \emph{line width illusion} even though the depiction is numerically sound.
% Furthermore, design choices during implementation \citep{schonlau:2003} may
%reduce the impact of such limitations.
%%

\section{Common angles}





\begin{figure}[htbp] %  figure placement: here, top, bottom, or page
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\linewidth]{images/caplot} 

}



\end{knitrout}

%   \centering
%   \includegraphics[width=\linewidth]{images/ca-titanic} 
   \caption{ \label{fig:ca-titanic} Common angle plot of the Titanic data. }
  \end{figure}

Figure \ref{fig:ca-titanic} shows a common angle plot of the same data as the hammock plot.

As in the previously discussed display types ribbons are drawn between categories with widths  that are proportional to  the number of records they represent.

In order to ensure that  widths of all bands are  comparable without any distortion, their slopes  are artificially made the same in the following manner: 
assuming a vertical display as shown in figure \ref{fig:ca-titanic},  connecting bands between  categories  are a combination of a vertical  segment, a  segment under a pre-specified angle $\theta$, followed by another vertical  segment.  
The pre-specified angle $\theta$ (between the line and the vertical band) is given as --at most-- the angle of the longest connecting line between two categories of neighboring variables. 
This makes the width of ribbons  comparable without being affected by the distortion, as all ribbons are sharing at least one segment under the same angle. 


Common angles, plus the related methods of hammock plots and parallel sets are implemented in the  package \texttt{ggparallel} based on the \texttt{ggplot2} \citep{ggplot2} plotting framework in the software R 2.15.1 \citep{R}. The ggparallel package is freely available from CRAN (http://www. r-project.org/). The colors for the plots have been chosen using color schemes suggested by the ColorBrewer project \citep{colorbrewer}, as implemented in the R package RColorBrewer \citep{RColorBrewer}.

\section{Usability Testing}
\subsection{Test} \label{test}

To determine the effectiveness of the common angle plot, we conducted a user study in the form of a survey asking participants to provide responses regarding the structure in two data sets with predominantly categorical variables. The Titanic data  includes class, sex, age, and survival status for each person on board of the Titanic \citep{dawson:1995}. The gene data  was retrieved from the UCSC Genome Browser \citep{ucsc:2002} and includes chromosome location for genes involved in one of three metabolism pathways: steroid biosynthesis, caffeine metabolism and drug metabolism.
For each data set, participants were asked to provide responses for three tasks that analysts routinely perform as part of exploratory data analysis:
\begin{description}
\item[{\bf Task I}:] simple comparison task, chosen to be unaffected by any illusion. Performance on this task should be comparable across designs.
\item[{\bf Task II}:] simple ordering, involving three pairwise comparisons, some of which are affected by the line width illusion or its reverse. 

\item[{\bf Task III}:] more complex ordering task with at least six pairwise comparisons, some of which are affected by either illusion.
 \end{description}
 
Each participant was presented with two of the three types of displays. 
For each display, the participant was asked to complete each of the three tasks for each data set. All participants were evaluated using the same set of questions with multiple choice options as detailed in Appendix \ref{app2}, regardless of display type or order. Participants were all shown the Titanic data first, then the gene data.  %one for all three tasks related to the same data set.
This resulted in a crossover design of  a total of six unique combinations of data and display as shown in Table \ref{tab:designs} allowing for comparisons of display types and tasks while  simultaneously adjusting for individuals' different skill sets and learning effect.

The choice to show only two of the three possible types of displays to a participant was made to encourage  participation by reducing the amount of time needed for its completion. 


\begin{table}[htbp]
\centering
\begin{tabular}{rrrrrrr}
Titanic Data & PS & CA & H & PS & CA & H \\ 
Genes Data & CA & PS & PS & H& H & CA \\ \hline
\#responses &  8 (9) &  6 (7) &  8 (9) &  6 (7) & 10 (11) & 8 (8)\\ 
\end{tabular}
\caption{\label{tab:designs} Overview of study design and participation numbers. The number in parenthesis indicates the number of participants completing the first block, but not the second.}
\end{table}



\subsection{Results}\label{results}
We are investigating three different aspects  of the experiment in this section: first,  assessing general performance on the tasks according to percentage of correct responses, second, investigating the extent of variability due to subject-specific abilities, and finally exploring of the space of answers for the more complex ordering Task III.
\subsubsection*{Correctness of Answers}
Answers for each survey question  were recoded in binary form according to correctness (with 1 for correct answers, and 0 otherwise). This forms the basis for the evaluation of performance of the different designs.

%In a first model, $M1$, we are only interested in the overall difference in performance between designs. We can express this as a model of the form
%\begin{equation}\label{model1}[M1]
%\quad\quad g(P(y_i=1)) = \mu + d_{j(i)} + u_{k(i)} + \varepsilon_i \quad\quad
%\end{equation}
%where $P(y_i=1)$ is the probability that the $i$th response is correct, for $i = 1, ..., n$. $g(.)$ is the transformation (link function) of the response. Here, we make use of the logit link, i.e.
%\begin{eqnarray*}
%g(P(y_i=1)) &=& \text{logit } P(y_i=1) = \\
%&=& \log P(y_i=1) - \log P(y_i=0).
%\end{eqnarray*}
%$d_{j(i)}$ is the parameter measuring the effect of design $j$ ($j = C, H, P$ for \underline{C}ommon Angle, \underline{H}ammock plot, and \underline{P}arallel sets plot), $u_{k(i)}$ is the effect of participant's $k$ individual skills in evaluating these plots, $k \in \{1, ..., 52\}$. The assumption is that skills are independent and normally distributed with an expected value of zero and a variance of $\sigma_u^2$.
%$\varepsilon_i$ is, similarly to a regular linear model, assumed to be independently distributed according to a normal distribution with mean of zero and variance $\sigma^2$.



%Table \ref{coef1} gives an overview of the model coefficients and their estimates. The effect of the common angle plot is used as a baseline, i.e all the effects shown are differences with respect to the performance of common angle plots. Both hammock plots and parallel sets  have negative effects on the correctness of the response. This indicates a significantly worse performance of these designs than under the common angle plot.

Table \ref{raw} shows percentages of correct answers for each question under each design. Bold numbers indicate significantly different (worse) performance of a design compared to the common angle plot based on a generalized linear model with random effects to adjust for individuals' abilities. The model explains 77.4\% of the total variability, corresponding to a highly significant deviance of 452.7 ($p$-value~$<\!\!\!< 0.0001$).

%The model used is a logistic regression estimating the odds of a correct answer for a specific task and design, while allowing for differences in subject-specific ability:
%%Model $M2$ extends the first model by including both  effects for individual questions and the interaction effects with each design in the following form:
%\begin{eqnarray}\nonumber
%  \ \ \qquad \text{logit}(P(y_i=1)) =  \qquad\qquad\qquad\qquad\qquad&&\\ \label{m2}
%\mu + d_{j(i)}  + q_{q(i)} + p_{j(i),q(i)} + u_{k(i)} + \varepsilon_i 
%\end{eqnarray}
%
%$\mu$ is the baseline 
%$d_{j(i)}$ is the parameter measuring the effect of design $j$ ($j = C, H, P$ for \underline{C}ommon Angle, \underline{H}ammock plot, and \underline{P}arallel sets plot), $u_{k(i)}$ is the effect of participant's $k$ individual skills in evaluating these plots, $k \in \{1, ..., 52\}$. The assumption is that skills are independent and normally distributed with an expected value of zero and a variance of $\sigma_u^2$.
%$\varepsilon_i$ is, similarly to a regular linear model, assumed to be independently distributed according to a normal distribution with mean of zero and variance $\sigma^2$.
%$q$ indicates the effects on performance for  each question, where $q(i)$ describes one of the questions $\{A1, A2, A3, B1, B2, B3\}$. $p$ is the parameter for the interaction effect of design and question, its index is a tuple consisting of a combination of a question and design. 
%

\begin{figure*}
\centering
\includegraphics[width=\textwidth]{model-summary.pdf}
\caption{\label{fig:model-summary}Overview of performance across tasks and designs. Points show average performance of subjects on each of the tasks, lines represent 95\% confidence intervals adjusted for multiple comparisons. The letter at the front of each panel allow for an evaluation of significance of pairwise comparisons: if two averages do not share a letter, they are significantly different at a level of 0.05.}
\end{figure*}

The observed results are in line with our expectations:
as we aimed for, task I does not show any significant differences between the designs and has overall the highest percentage of correctness reflecting its low difficulty level. Generally, difficulty of levels seems to increase with complexity of the tasks.

Parallel sets were affected the most by the line width illusion and show significantly worse performance for tasks II and III in the Titanic data, and for task III in the genes data. The performance on task II in the genes data is borderline non-significant, but shows a negative trend.
Hammock plots led to significantly worse performance than common angle plots in the two questions that were affected by the reverse line width illusion, while they show equal performance as common angle plots for the other questions. For task II in the genes data,  hammock plots have the overall best performance  across designs-- but this  does not  constitute a significant improvement over the performance of the common angle plot. Figure~\ref{fig:model-summary} gives an overview of  performance of each design on all tasks. 



%long <- ddply(survey, .(qu, design), summarize,
%              n=length(qu),
%              mean=mean(correct),
%              sd=sd(correct))
%long$label <- sprintf("%.1f (%.2f)", long$mean*100, long$sd/long$n*100)
%xtable(acast(long, qu~design, value.var="label"))
%
%% latex table generated in R 2.15.1 by xtable 1.7-0 package
%% Wed Mar 27 23:20:10 2013
\begin{table}[ht]
\begin{center}
\begin{tabular}{llrrrr}
  \hline
Task & Data & \multicolumn{3}{l}{Design} \\
& & \multicolumn{1}{l}{CA} & \multicolumn{1}{l}{H}  & \multicolumn{1}{l}{PS}  \\ 
  \hline
 I & Titanic & 85.2 (0.66) & 76.5 (0.84) & 68.8 (0.98) \\ 
& Genes & 93.8 (0.51) & 83.3 (0.78) & 83.3 (0.90) \\ [3pt]
 II& Titanic & 72.2 (2.56) & {\bf 17.6} (2.31) & {\bf 25.0} (2.80) \\ 
& Genes & 75.0 (2.80) & 87.5 (2.13) & {\bf 57.1} (3.67) \\ [3pt]
III & Titanic & 66.7 (2.69) & {\bf 41.2} (2.98) & {\bf 6.2} (1.56) \\ 
& Genes & 68.8 (2.99) & 68.8 (2.99) & {\bf 7.1} (1.91) \\ \hline
\end{tabular}
\end{center}
\caption{\label{raw} Percentages (standard deviation) of correct responses for each task and design. Bold numbers indicate significant difference from common angle plot performance.  }
\end{table}

%Model $M2$ extends the first model by including both  effects for individual questions and the interaction effects with each design in the following form:
%\begin{eqnarray}\nonumber
%[M2]  \ \ \qquad g(P(y_i=1)) =  \qquad\qquad\qquad\qquad\qquad&&\\ \label{m2}
%\mu + d_{j(i)}  + q_{q(i)} + p_{j(i),q(i)} + u_{k(i)} + \varepsilon_i 
%\end{eqnarray}
%$d_{j(i)}$ is the parameter measuring the effect of design $j$ ($j = C, H, P$ for \underline{C}ommon Angle, \underline{H}ammock plot, and \underline{P}arallel sets plot), $u_{k(i)}$ is the effect of participant's $k$ individual skills in evaluating these plots, $k \in \{1, ..., 52\}$. The assumption is that skills are independent and normally distributed with an expected value of zero and a variance of $\sigma_u^2$.
%$\varepsilon_i$ is, similarly to a regular linear model, assumed to be independently distributed according to a normal distribution with mean of zero and variance $\sigma^2$.
%$q$ indicates the effects on performance for  each question, where $q(i)$ describes one of the questions $\{A1, A2, A3, B1, B2, B3\}$. $p$ is the parameter for the interaction effect of design and question, its index is a tuple consisting of a combination of a question and design. 
%
%%Figure \ref{fitted.m2} gives an overview of the goodness of fit of model $M2$ -- histograms of fitted values are drawn facetted by levels of the dependent variable. For correct responses fitted values are highly left skewed, with most values  above 0.5. For wrong answers we see a symmetric, if not quite as clear-cut picture: fitted values are skewed right. 
%%Overall, Model $M2$ is a significant improvement over model $M1$ (a corresponding log-likelihood ratio test is significant at a level of $<\!\!\!< 10^{-8}$).
%%Table \ref{model2} shows an overview of the  parameters and their estimates for model $M2$. After adjusting for individuals' skills parallel sets performs significantly worse than common angle plots in three of the six questions. 
%%
%%\begin{figure}
%%\includegraphics[width=\linewidth]{fitted-m2}
%%\caption{\label{fitted.m2} Histograms of fitted values under model $M2$, facetted by actual performance of participants. On the left, correct responses are shown. The histogram of fitted values is skewed to the right, with most values above 0.5. The histogram on the right corresponds to wrong answers. There are fewer wrong answers, and they tend to have low fitted values, but there are more false positives among them than false negatives for correct answers. }
%%\end{figure}
%
\subsubsection*{Individuals' skill levels}
\begin{figure}
\centering \includegraphics[width=.7\linewidth]{hist-skills}
\caption{\label{skills}Histogram of the predictions of subject-specific skills. }
\vspace{-0.2in}
\end{figure}  
Figure \ref{skills} shows an overview of the predicted skill for each participant under the model. Skills are quite varied between  -1.52 and  1.34, but
a Kolmogorov-Smirnov test  does not show significant deviation from a normal assumption ($p$-value 0.089).
On the scale of the dependent variable the range in individuals' skills translates to a $17.5 = e^{1.34 - (-1.52)}$ fold increase in the probability of answering a question on the survey correctly between participants with the best skill set and the worst.

%In the next section we will investigate the results from the survey in further detail for some questions, and highlight the link to the line width illusion and its reverse.

\subsubsection*{Evidence for line width illusions}

Task III for the Titanic data required participants to order  class levels  according to the number of survivors, fewest to highest. 

%To quantify distance between each pair of permutations, the Cayley distance is used.The  Cayley  distance is defined as the minimal number of transpositions (i.e. swaps of two elements) necessary to transform one permutation into another.
%The Cayley distance defines a way to quantify the distance between  each pair of permutations; the Cayley distance is defined as the minimal number of transpositions, i.e. swaps of two elements,  necessary to transform one permutation into the other.



There are 4! = 24 distinct orderings of the levels, corresponding to all permutations of length four. Some orderings are closer to one another than other orderings. 
The Cayley distance allows us to quantify this distance; the Cayley distance between two orderings is defined as the smallest number of switches necessary to get from one ordering to the other. Visually, this corresponds to a graph; each node represents one ordering, and two nodes are connected by an edge, if only a single switch is necessary to move from one ordering to the other, i.e. if the Cayley distance between these nodes is one.
This results  in a  regular graph of degree six, i.e. each  node is connected to six other nodes. Between any two nodes, the Cayley distance on the graph is equivalent to the length of the shortest connecting path between the two nodes.
Figure \ref{cubes} shows an overview of the permutation space together with an overview of the survey results. 

The colored dots on top of the graph correspond to the responses from the survey. The size of these dots is proportional to the number of observers choosing this particular ordering. It becomes obvious from the three graphs in figure \ref{cubes} that
the answers to different designs occupy quite different regions, while answers based  on the same design are quite close --  usually separated by only one edge. 

The correct ordering, as well as the orderings assuming the line width illusion and its reverse are marked by symbols. Answers for the common angle plot are centered around the correct answer, while responses to parallel sets  cluster around the response corresponding to the line width illusion. Answers based on the hammock design are split evenly between the correct answer and the answer corresponding to the  inverse line width illusion. Table \ref{a2} gives an overview of all responses to task III for the Titanic data.

\begin{table}[ht]
\begin{center}
\begin{tabular}{rrrrl}\hline
Order  & CA & H & PS\\
  \hline
  Crew, 1st, 3rd, 2nd &  &  2 &  \\ \rowcolor{LightGrey}
  2nd, 1st, 3rd, Crew &  &  6 &  & reverse line width illusion \\ 
   Crew, 3rd, 1st, 2nd &  &  1 &  1 \\ \rowcolor{LightGrey}
  2nd, 3rd, 1st, Crew & 12 & 7 & 1 & correct\\  
  2nd, 3rd, Crew, 1st & 1 &  1 &  2 \\
  Crew, 3rd, 2nd, 1st &  2 &  &  \\ 
  3rd, 2nd, Crew, 1st &  1 &  &  \\ 
  1st, 2nd, 3rd, Crew &  1 &  &  1 \\ 
  1st, 3rd, Crew, 2nd &  1 &  &  2 \\ \rowcolor{LightGrey}
  Crew, 2nd, 3rd, 1st &  &  & 6 &  line width illusion\\  
  2nd, Crew, 3rd, 1st &  &  &  3 \\ 
   \hline
  Total & 18 & 17 & 16 \\ 
   \hline
\end{tabular}
\end{center}
\caption{\label{a2} Responses to task III in the Titanic data: order levels of Class by the number of survivors (smallest to largest). }
\end{table}

%
Common angle plots show the best performance in terms of correctness (66.7\% on 18 responses), compared to a correctness of 6.2\% for the parallel sets plot on 16 responses, constituting a significantly better performance of the  common angle plot at a level of $< 0.0001$, based on a Mantel-Haenszel test (the difference in performance to the hammock plot is not significant with $p$-value of 0.1359, but the hammock plot performs also significantly better than parallel sets plot with a $p$-value of 0.0016 ).
While the intuitive assessment of lines by their width orthogonal to their direction is well known, it is surprising to see its strength: in this particular setting, it is strong enough to `shrink' the horizontally widest line for six out of 16 participants by at least  44\%, from 212 to below 118, and a further three participants perceived a  shrinkage to below 178,  a distortion factor of at least 16\%.

\begin{figure*}
\includegraphics[width=\linewidth]{cubes}
\caption{Answers to task III in the Titanic data -- each node corresponds to a single ordering of the levels in variable 'Class'. Lines are drawn between orderings that are only one swap of levels apart. The colored dots show responses from the survey, their sizes depend on the number of responses for each ordering. }
\label{cubes}
\end{figure*}



\subsubsection*{Opinion on common angle plots}
Answers to the question of `which chart did you like better?' are shown in table \ref{tab:prefer}. There is a  clear endorsement in favor of common angle plots versus the other two types of displays.
The most common reason cited for the choice was a facilitated comparison of width, area or ``size", 
%3 saw the common angle plots as preferable, and the remaining answers related to a 'more logical' structure or generally 'easier' choice.
The only consistent complaint against common angle was a preference for straight lines.
%Reasons for not preferring common angle plots boiled down to a preference for straight lines.
 This purely aesthetic preference is deeply rooted and in our opinion the biggest challenge for common angle plots.
% latex table generated in R 2.15.1 by xtable 1.7-0 package
% Wed Oct 31 10:28:55 2012
\begin{table}[ht]
\begin{center}
\begin{tabular}{cccrrr}
  \hline
&\multicolumn{5}{r}{Which chart did you like better?}\\
&&& Chart 1 &  Chart 2 \\ 
  \hline
  PS &vs&  {\bf CA} & 2 & \bf 6 \\ 
 {\bf  CA} & vs &  PS & \bf 4 & 2 \\ 
  H & vs &   {\bf  CA} & 3 & \bf 5 \\ 
   {\bf  CA} & vs &  H & \bf 8 & 2 \\ 
  H & vs &  PS & 3 & 5 \\ 
  PS & vs &  H & 1 & 5 \\ 
   \hline
\end{tabular}
\caption{\label{tab:prefer} Preferences for first or second chart across all six combinations of questions and chart types. }
\vspace{-0.3in}
\end{center}
\end{table}

\subsection{Methods}

The survey was created using the Qualtrics Labs, Inc software (www.qualtrics.com). For survey contents, see Appendix~\ref{app2}. The study design is presented in section \ref{test}. All models are fit in the {\tt lme4} package~\citep{lmer} within the software framework of {\tt R} 2.15.1 \citep{R}. Comparisons are adjusted for multiple testing using the {\tt multcomp} package~\citep{multcomp} and evaluated for pairwise significances using the {\tt effects} package~\citep{effects}.


\section{Discussion}
There is strong support from the user study that common angle plots help the reader to overcome issues arising from the line-width illusion and its reverse. This might come as a surprise, in particular, as common angle plots break one of the nice mathematical properties that parallel sets have:
the area of a connecting line in parallel sets has a constant  overall area  independent of the angle under which it is drawn. Both hammock plots and common angle plots break this property. It does not seem, however, that the audience picks up on area as the main property of the displays. This might be also influenced by the relative high difficulty of the task of comparing areas \citep{heer:2010, kong:2010}, in particular, if they suffer from  (1) extreme aspect ratios of the rectangular shape or (2) are drawn under different orientations, both of which apply to parallel sets. 

There are several other issues that common angle plots do not address in the visualization of categorical data, that should be noted at this point: \begin{itemize}
\item Large number of levels in a variable introduce a lot of line crossings, which affects the overall effectiveness of the display. The number of line crossings is the same in parallel sets plots, but hammock plots reduce the number of crossings by centering all lines.
\item The use of color to separate levels is also problematic for large number of categories in a variable, as it leads to  palettes with very similar colors.
\end{itemize}


%For data with a large number of variable levels, common angle plots may introduce more line crossings than  hammock plots, while the number of crossings is the same between parallel sets and common angles. This  may affect the effectiveness of the overall display. Use of color may also be problematic with many variable levels, as readers may have difficulty resolving a palette of colors separated by small intervals. Certainly, resolving many colors is difficult for audience with a history of color blindness and may be 
%technically limited in print applications. The issue of color is consistent regardless of display choice 
%between parallel sets, hammock plots or common angles. 
%Further study is necessary to resolve the potential 
%for distortion in different application, especially the impact of bands displayed with extreme values for 
%$\theta$, a known source of perceptual inaccuracy~\citep{heer:2010}.

Apart from these problems that will have to be solved in a different framework of plots, there are several opportunities for extending common angle plots.
One opportunity for extension lies in the algorithm to determine the thickness of the connecting line. In the
tested version of common angle plots, the line width was not explicitly defined - the line width is a byproduct of 
specified $\theta$ for a band that connects marginal bars. Using an additional hammock adjustment as given in equation \ref{adjust} in the slanted section of the line segment, we can keep the bandwidth constant, resulting in a  common angle-hammock plot hybrid that bears further investigation.
A drawback of this approach is that the sum of the bandwidths $w_h$ will no longer match the widths of the marginal bars. 
This may create a additional processing burden placed on the audience to map the relationship between 
band width and the with of marginal bars. 
Both hammock plots and  this modification of common angles face  
the issue of band \emph{area} as context to support reader interpretation of $w_o$. Since the band
area is now related to the incident angle $\theta$, changes in the display aspect ratio may have a distortion 
effect. In the study described in this paper, this effect was not evaluated and aspect ratios were kept constant.



\begin{figure}[htbp]
\centering
\includegraphics[width=\linewidth]{images/adj-angle}
\caption{\label{adj.angle}Common angle plot of Titanic data using hammock correction.}
\end{figure}
In the original paper, parallel sets were introduced to reflect a hierarchy of variables. 
Prior examples in this paper show sets of two-dimensional plots to focus on the association between 
pairs of variables. 
With color coding, it is possible to show hierarchies in all of the types of displays.
Figure \ref{tit-hierarchy}
shows a common-angle plot  with a hierarchy: survivors of the disaster are marked in blue, 
non-survivors by orange. From top to bottom of the plot a hierarchy is drawn, considering first 
survival, then gender, followed by age and finally class membership. The coloring tracks 
survival status throughout the hierarchy, the layout in a common angle plot makes comparisons 
valid across all levels. This is of particular importance in hierarchical displays, which
by definition have a larger number of smaller groups than displays without a hierarchy exacerbating 
problems induced by the line width illusion.


\begin{figure}[hbtp]
\includegraphics[width=\linewidth]{ca-hierarchy}
\caption{\label{tit-hierarchy} Common angle plot of the Titanic data using a hierarchical structure in the variable (cf. to parallel sets chart in \citep{davies}). }
\end{figure}


Another opportunity for extending common angle plots is to add interactivity. It is important to note that
any additions of functionality via interactivity should not come at the expense of developing distortion-free
displays. Simply augmenting a plot that has distortion of the \emph{line width illusion} variety does not eliminate
the presence of that illusion, rather it obfuscates the message of the display. A display with visual cues in conflict
with the interactive feedback introduces a higher cognitive load by asking the audience to decide on one of the sources of information.
In the case where interactive feedback (e.g. summary data on mouse hover) is accurate when the visual cues
suggest alternate interpretation, a mistrust of the graphical presentation may develop. In an extreme case,
the user may develop a mistrust of their own perception, which would reduce effectiveness of all data displays, 
regardless of the presence of any perceptual distortion. In the alternate case, where the audience chooses to
rely on perception over interactive feedback, it is possible that distortions in displays that are part of 
the initial exploratory analysis may lead to research choices that are unsupported by data. This is both a waste of resources and, when human or animal subjects are involved, may lead to ethical violations.


\section{Conclusion}
We have proposed a new chart type for visualizing multivariate categorical data, common angle plots, 
and tested its usability compared to existing charts that perform a similar function. Results from user testing
indicate
that common angle plots effectively communicate underlying data without encouraging perceptual distortion of the 
\emph{line width} illusion.
Two other chart types which address visualization of multivariate categorical data: parallel sets and hammock plots, 
are subject to the line width illusions due to 
contextual framework. Audiences perceive parallel sets with distortion due to a natural tendency to 
evaluate line width in the orthogonal direction while data is mapped to the horizontal width.
For hammock plots a correction is made to map data to the orthogonal width, however the centering of the lines creates a strong contextual cue that encourages an evaluation of line widths using the
horizontal measure, leading to a (\emph{reverse line width illusion}). Common angles avoids the perceptual distortion 
associated with either version of the illusion regardless of the underlying data set.

%% if specified like this the section will be ommitted in review mode
\acknowledgments{
The survey for this study was carried out with approval from  IRB-ID 12-204. 
}

% if have a single appendix:
%\appendix[Proof of the Zonklar Equations]
% or
%\appendix  % for no appendix heading
% do not use \section anymore after \appendix, only \section*
% is possibly needed

% use appendices with more than one appendix
% then use \section to start each appendix
% you must declare a \section before using any
% \subsection or using \label (\appendices by itself
% starts a section numbered zero.)
%


\begin{appendix}%\appendices
\section{Survey }\label{app2}

At the survey start, participants were presented a brief tutorial regarding the different plot types. The tutorial can be found at \url{http://mariev.net/tutorial.html}

Completion of all survey questions was anticipated to take 10 - 15 minutes.
No personally identifiable information was collected, nor was any compensation offered.   

\noindent The questions pertaining to the Titanic data were: 
\begin{description}
\item[\bf Task 1: ]\emph{ Agree, Disagree or Don't Know/Can't Determine with the following statements:}
\begin{itemize}
\item There were an approximately equal number of Male and Female Survivors
\item The group with largest number of travelers was Female Survivors
\item There were more Male Non-Survivors than number of males in First and Second Class Combined
\end{itemize}

\item[\bf Task 2: ]\emph{ Order the following groups by number, fewest to most}
\begin{itemize}
\item 1st Class female passengers
\item Male Survivors
\item Crew Survivors
\end{itemize}

\item[\bf Task 3: ]\emph{ Order the categories of Class by number Survived, fewest to most.} 
\begin{itemize}
\item 1st
\item 2nd 
\item 3rd
\item Crew
\end{itemize}
\end{description}


\noindent The questions pertaining to the gene data were: 


\begin{description}
\item[\bf Task I:]\emph{ Agree, Disagree or Don't Know/Can't Determine with the following statements:}
\begin{itemize}
\item There are about the same number of genes in the group "steroid biosynthesis:chromosome 1" as in the group "caffeine metabolism: chromosome 8"
\item The group with the greatest number of genes is "drug metabolism:chromosome 4"
\item there are more genes involved in the group "drug metabolism: chromosome 1" than all genes involved in the caffeine metabolism pathway
\end{itemize}

\item[\bf Task 2: \ ]\emph{ Order the following chromosomes by number of genes involved, fewest to most.}
\begin{itemize}
\item steroid biosynthesis :: chromosome X
\item steroid biosynthesis :: chromosome 4
\item drug metabolism :: chromosome X
\end{itemize} 

\item[\bf Task 3: \ ] \emph{ Order the following chromosomes by number of genes involved in steroid biosynthesis pathway, fewest to most.}
\begin{itemize}
\item chromosome 1
\item chromosome 4
\item chromosome 8 
\item chromosome X
\end{itemize}

\end{description} 


%Appendix one text goes here.
%
%% you can choose not to have a title for an appendix
%% if you want by leaving the argument blank
\section{Participants' demographics}
All students, staff and faculty from Iowa State University programs in Statistics, Bioinformatics and Computational Biology and Human Computer Interaction were invited to participate by email. 93 individuals accessed the survey;
86 participants gave consent, 15  of those dropped out right after, 20 went to the training site and did not return.
Out of the remaining 51 participants, 46  individuals submitted responses for all questions and five gave responses to the first block of questions.

Participants used their own personal computing devices to access the survey, 
a majority of participants used Intel Mac OS X (versions ranging from 10.6.8 to 10.8.2), while Windows was the next most common operating system. The preferred choice of browser was  Firefox, followed by Chrome. For two participants, the Qualtrics survey software was unable to capture operating system or browser information. 
%Appendix two text goes here.

%\section{Selected survey results}
%Responses to task II, Titanic data are shown in table \ref{a3}. Results are clearly showing clustering depending on the designs. Answers based on parallel sets cluster around the solution corresponding to the line-width illusion, while the hammock plot leads to solutions around the reverse line width illusion.
%
%\begin{table}[ht]
%\begin{center}
%\begin{tabular}{rrrrl}
%Order & CA & H & PS\\
%  \hline
%c, b, a &  &  2 &  \\
%a, b, c &  1 &  12 &  & reverse line width illusion\\ 
%a, c, b & 13 &  3 &  4 & correct\\ 
%b, c, a &  2 &  &  1 \\ 
%c, a, b &  2 &  & 9 & line width illusion\\ 
%b, a, c &  &  &  2 \\ 
% \hline
%  Total & 18 &  17 & 16 \\ 
%   \hline
%\end{tabular}
%\end{center}
%\caption{\label{a3}Responses to task II, Titanic data: order combinations from smallest to largest, where 'a' is first class female, 'b' are male survivors, and 'c' are crew survivors. }
%\end{table}
%  
%\begin{table}[ht]
%\begin{center}
%\begin{tabular}{clrrrl}
%  Qu & Design & \rotatebox{90}{Correct} & \rotatebox{90}{Incorrect} & \rotatebox{90}{No Answer}   & Reason\\ \hline
%  \hline
%1 & common &   14 &  2 &   0 \\ 
%   & hammock &   15 &  0 &   1 \\ 
% & parallel &   7 &   7 &   0 & line width illusion\\ \hline
%2 & common &  16 &   0 &   0 \\ 
%& hammock &   9 &   7 &   0 & reverse line width illusion\\ 
%& parallel &  14 &   0 &   0 \\ \hline
%3& common &  15 &   1 &   0 \\ 
%& hammock &  16 &   0 &   0 \\ 
%& parallel &  14 &   0 &   0 \\ 
%   \hline
%\end{tabular}
%\end{center}
%\caption{\label{tab:b1}Responses to task I, gene data}
%\vspace{-0.25in}
%\end{table}
%
%
%Table \ref{tab:b1} shows a summary responses for Task I, gene data with possible answers ``agree", ``disagree", and ``don't know".
%The first two questions are  examples, where the line width illusion, and its reverse will lead to answers that differ from the correct answer. Parallel sets  are susceptible to the line width illusion, while hammock plots suffer from the reverse. The data shows that in about 50\% of the responses we can see this difference. Seven out of 14 answers for the parallel sets plots in question 1 deviate from the correct answer, and seven out of 16 responses corresponding to hammock plots in question 2 show the wrong answer.

%\section{Model results}
%
%% xtable(summary(m4)@coefs)
%% latex table generated in R 2.15.1 by xtable 1.7-0 package
%% Fri Oct 12 09:12:32 2012
%\begin{table}[ht]
%\begin{center}
%\begin{tabular}{rrrrrl}
%  \hline
% & Estimate & Std. Error & $z$ value & Pr($>$$|$z$|$) & \\ 
%  \hline  
%$\mu$ & 2.68 & 0.61 & 4.35 & 0.00  & ***\\ [5pt]
%Design\\
%  $d_C$ & 0.00 & -- & -- & -- \\ 
%  $d_H$ & -1.06 & 0.83 & -1.28 & 0.20  \\ 
%  $d_P$ & -0.57 & 0.86 & -0.66 & 0.51 \\ [5pt]
%Questions\\
%  $q_{A1}$ & 0.00 & -- & -- & -- \\ 
%  $q_{A2}$  & -1.85 & 0.74 & -2.50 & 0.01 &* \\ 
%  $q_{A3}$  & -1.11 & 0.77 & -1.44 & 0.15 \\ 
%  $q_{B1}$ & 0.55 & 0.96 & 0.58 & 0.56 \\ 
%  $q_{B2}$  & -1.69 & 0.88 & -1.91 & 0.06 &. \\ 
%  $q_{B3}$  & -1.31 & 0.92 & -1.43 & 0.15 \\ [5pt]
% 
%Interaction \\
%$p_{H, A1}$ &  0.00 & -- & -- & -- \\
%$p_{P,A1}$ &  0.00 & -- & -- & -- \\
%$p_{H, A2}$ &  -3.29 & 1.55 & -2.13 & 0.03 & *\\ 
%$p_{P,A2}$ & -3.03 & 1.33 & -2.28 & 0.02 &*\\ 
%$p_{H,A3}$ &-2.61 & 1.17 & -2.24 & 0.03  & * \\ 
%$p_{P,A3}$ & -2.60 & 1.16 & -2.23 & 0.03 &*\\ 
%$p_{H,B1}$ &-0.26 & 1.21 & -0.22 & 0.83 \\ 
%$p_{P,B1}$ &-0.81 & 1.24 & -0.65 & 0.51 \\ 
%$p_{H,B2}$ & 1.03 & 1.22 & 0.85 & 0.40 \\ 
%$p_{P,B2}$  & -3.48 & 1.63 & -2.14 & 0.03 &*\\ 
%$p_{H,B3}$ & 1.97 & 1.37 & 1.44 & 0.15 \\ 
%$p_{P,B3}$ & -0.62 & 1.26 & -0.50 & 0.62 \\   
%   \hline
%\multicolumn{6}{l}{Signif. codes:  0 `***' 0.001 `**' 0.01 `*' 0.05 `.' 0.1 ` ' 1 }
%\end{tabular}
%\end{center}
%\caption{\label{model2} Model fit for measuring correctness of answers in the survey, detailing performance of designs on each question. All design comparisons are with respect to the common angle plot. }
%\end{table}



\end{appendix}

\bibliographystyle{apalike}
%\bibliographystyle{plain}
%%use following if all content of bibtex file should be shown
%\nocite{*}
\bibliography{references}
\end{document}
